### ISSUE TITLE
12041 trees, 20390 tree censuses

### ISSUE THREAD

**Issue by mirunaish** [dali-lab/inforest#247]
round 2:
12273 trees, 12244 censuses
~30 uncensused trees remain
~100 duplicated tags, ~90 on plots 0011 and 0111
some trees with species abcde

made trees with missing dbh / species flagged

the fact that the ratio of  censuses to trees has remained constant worries me. (used to be 5000-8000)
i'm 75% sure that there are no trees with multiple tree censuses left
i'm 90% sure that there are no tree censuses on a deleted tree
none of the tree census labels were on a fake census

09009 has a ploty but no plotx

**Comment by mirunaish** [comment]
there's about 500 tree censuses that have no data and multiple trees have two identical tree censuses

**Comment by Heyomiranda** [comment]
[

![Image](https://user-images.githubusercontent.com/108059891/191614508-f3c047bb-3088-4053-adc2-a1e81d3a859a.jpeg)

](url)

**Comment by Heyomiranda** [comment]
check the database and clean up the error data
