### ISSUE TITLE
Visualization feature updates

### ISSUE THREAD

**Issue by Heyomiranda** [dali-lab/inforest#275]

**Comment by fpoon777** [comment]
Tried Customer Marker with option that stops the component rerender. 
But feature not tested because signup/login issue occured in the master branch repo

**Comment by mirunaish** [comment]
partner meeting notes:
- trees are translucent black dots in explore view
- trees same size, filter in settings to show relative sizes
- trees must be clickable in explore view and plot view, not edit view
- species filtering: one species colored, rest are gray
- show all of them as smallish dots when zoomed out, zoom in to click, ok if they are small or overlap when zoomed out

**Comment by fpoon777** [comment]
Finished adding x and y axis. Working on the database to show all the dots.
